markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 代码熊-TedCoder
host: tedcoder.com/
desc: Android应用开发者，喜欢捣鼓新生事物，对很多技术抱有兴趣，有代码洁癖，喜欢规划，不喜欢拖延。

custom:
    category:
        blog:  Blogs
        easy_note: About EasyNote
    categories:
      - name:  blog
        title: Blogs

      - name:  easy_note
        title: 烂笔头

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Ted
        email: xiong-wei@hotmail.com
        disqus: tedcoder.disqus.com	            # Disqus缩略标识
        gcse: 013980716105654176158:plxoomwkfey     # Google自定义搜索标识ID
        github: xiongwei-git	                    # GitHub账号
        gravatar: 71751d1077e8ed18ef53dbac4295fa60  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
